/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var Optmizar = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,16],$V1=[1,11],$V2=[1,12],$V3=[1,15],$V4=[1,13],$V5=[1,14],$V6=[5,19,21,24,26,27,29],$V7=[1,32],$V8=[1,33],$V9=[1,42],$Va=[1,41],$Vb=[1,43],$Vc=[1,44],$Vd=[1,45],$Ve=[1,46],$Vf=[1,47],$Vg=[1,48],$Vh=[1,49],$Vi=[1,50],$Vj=[1,51],$Vk=[1,52],$Vl=[1,53],$Vm=[8,23,25,34,35,36,37,38,39,40,41,42,43,44,45],$Vn=[17,18,21,25,33];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"Init":3,"Instructions":4,"EOF":5,"Instruction":6,"DECLARACION":7,";":8,"ETIQUETA":9,":":10,"SALTO":11,"CALL":12,"METODO":13,"NOTERMINAR_IMPRIMIR":14,"IF":15,"NUMBERR":16,"NUMBER":17,"DECIMAL":18,"t_if":19,"(":20,"ID":21,"SIGNO":22,")":23,"t_goto":24,"-":25,"ER_imprimir":26,"t_void":27,"{":28,"}":29,"=":30,"[":31,"]":32,"STRING_2":33,"+":34,"*":35,"/":36,"%":37,"<":38,"<=":39,">":40,">=":41,"==":42,"!=":43,"&&":44,"||":45,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:";",10:":",17:"NUMBER",18:"DECIMAL",19:"t_if",20:"(",21:"ID",23:")",24:"t_goto",25:"-",26:"ER_imprimir",27:"t_void",28:"{",29:"}",30:"=",31:"[",32:"]",33:"STRING_2",34:"+",35:"*",36:"/",37:"%",38:"<",39:"<=",40:">",41:">=",42:"==",43:"!=",44:"&&",45:"||"},
productions_: [0,[3,2],[4,2],[4,1],[6,2],[6,2],[6,2],[6,2],[6,1],[6,1],[6,2],[16,1],[16,1],[15,8],[15,8],[15,8],[15,9],[14,1],[13,5],[13,1],[12,3],[11,2],[7,3],[7,5],[7,6],[7,5],[7,5],[7,3],[7,6],[7,6],[7,8],[7,6],[7,7],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[9,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

        exports.Lista_errores= Lista_errores;
       
        return $$[$0-1];  
break;
case 2:
 $$[$0-1].push($$[$0]); this.$ = $$[$0-1];    
break;
case 3:
              this.$ = [$$[$0]];  
break;
case 4: case 5: case 6: case 7: case 10:
 this.$=$$[$0-1]; 
break;
case 8: case 9: case 33: case 34: case 35: case 36: case 37: case 38: case 39: case 40: case 41: case 42: case 43: case 44: case 45:
 this.$=$$[$0]; 
break;
case 11: case 12:
this.$=$$[$0];
break;
case 13: case 14: case 15:
this.$= new  condicion($$[$0-5],$$[$0-4],$$[$0-3],$$[$0],_$[$0-7].first_line);
break;
case 16:
this.$= new  condicion($$[$0-6],$$[$0-5],$$[$0-4],"-"+$$[$0],_$[$0-8].first_line);
break;
case 17:
this.$= new imprimir($$[$0],_$[$0].first_line);
break;
case 18:
 this.$=new metodo1($$[$0-3],_$[$0-4].first_line); 
break;
case 19:
 this.$=new metodo2(_$[$0].first_line);    
break;
case 20:
this.$= new llamada($$[$0-2],_$[$0-2].first_line);
break;
case 21:
this.$= new goto($$[$0],_$[$0-1].first_line);
break;
case 22:
 this.$= new declaracion3($$[$0-2],$$[$0],_$[$0-2].first_line);                
break;
case 23:
 this.$= new declaracion($$[$0-4],$$[$0-2],$$[$0-1],$$[$0],false,_$[$0-4].first_line);     
break;
case 24:
 this.$= new declaracion($$[$0-5],$$[$0-3],$$[$0-2],"-"+$$[$0],false,_$[$0-5].first_line); 
break;
case 25: case 26:
 this.$= new declaracion($$[$0-4],$$[$0-2],$$[$0-1],$$[$0],true ,_$[$0-4].first_line);     
break;
case 27:
 this.$= new declaracion1($$[$0-2],$$[$0],_$[$0-2].first_line);                
break;
case 28:
 this.$= new declaracion2($$[$0-5],$$[$0-3],$$[$0-1],true ,_$[$0-5].first_line);       
break;
case 29: case 31:
 this.$= new declaracion2($$[$0-5],$$[$0-3],$$[$0],false,_$[$0-5].first_line);       
break;
case 30:
 this.$= new declaracion4($$[$0-7]+"["+$$[$0-5]+"]="+$$[$0-2]+$$[$0-1]+$$[$0],_$[$0-7].first_line);       
break;
case 32:
 this.$= new declaracion2($$[$0-6],$$[$0-4],"-"+$$[$0],false,_$[$0-6].first_line);       
break;
case 46:
 this.$=new etiqueta($$[$0],_$[$0].first_line );
break;
}
},
table: [{3:1,4:2,6:3,7:4,9:5,11:6,12:7,13:8,14:9,15:10,19:$V0,21:$V1,24:$V2,26:$V3,27:$V4,29:$V5},{1:[3]},{5:[1,17],6:18,7:4,9:5,11:6,12:7,13:8,14:9,15:10,19:$V0,21:$V1,24:$V2,26:$V3,27:$V4,29:$V5},o($V6,[2,3]),{8:[1,19]},{10:[1,20]},{8:[1,21]},{8:[1,22]},o($V6,[2,8]),o($V6,[2,9]),{8:[1,23]},{10:[2,46],20:[1,26],30:[1,24],31:[1,25]},{21:[1,27]},{21:[1,28]},o($V6,[2,19]),o($V6,[2,17]),{20:[1,29]},{1:[2,1]},o($V6,[2,2]),o($V6,[2,4]),o($V6,[2,5]),o($V6,[2,6]),o($V6,[2,7]),o($V6,[2,10]),{16:31,17:$V7,18:$V8,21:[1,30]},{21:[1,34]},{23:[1,35]},{8:[2,21]},{20:[1,36]},{16:38,17:$V7,18:$V8,21:[1,37]},{8:[2,22],22:39,25:$V9,31:[1,40],34:$Va,35:$Vb,36:$Vc,37:$Vd,38:$Ve,39:$Vf,40:$Vg,41:$Vh,42:$Vi,43:$Vj,44:$Vk,45:$Vl},{8:[2,27],22:54,25:$V9,34:$Va,35:$Vb,36:$Vc,37:$Vd,38:$Ve,39:$Vf,40:$Vg,41:$Vh,42:$Vi,43:$Vj,44:$Vk,45:$Vl},o($Vm,[2,11]),o($Vm,[2,12]),{32:[1,55]},{8:[2,20]},{23:[1,56]},{22:57,25:$V9,34:$Va,35:$Vb,36:$Vc,37:$Vd,38:$Ve,39:$Vf,40:$Vg,41:$Vh,42:$Vi,43:$Vj,44:$Vk,45:$Vl},{22:58,25:$V9,34:$Va,35:$Vb,36:$Vc,37:$Vd,38:$Ve,39:$Vf,40:$Vg,41:$Vh,42:$Vi,43:$Vj,44:$Vk,45:$Vl},{16:59,17:$V7,18:$V8,21:[1,61],25:[1,60]},{21:[1,62]},o($Vn,[2,33]),o($Vn,[2,34]),o($Vn,[2,35]),o($Vn,[2,36]),o($Vn,[2,37]),o($Vn,[2,38]),o($Vn,[2,39]),o($Vn,[2,40]),o($Vn,[2,41]),o($Vn,[2,42]),o($Vn,[2,43]),o($Vn,[2,44]),o($Vn,[2,45]),{21:[1,63]},{30:[1,64]},{28:[1,65]},{16:67,17:$V7,18:$V8,21:[1,66],25:[1,68]},{16:69,17:$V7,18:$V8},{8:[2,23]},{16:70,17:$V7,18:$V8},{8:[2,26]},{32:[1,71]},{8:[2,25]},{16:73,17:$V7,18:$V8,21:[1,72],25:[1,74]},o($V6,[2,18]),{23:[1,75]},{23:[1,76]},{16:77,17:$V7,18:$V8},{23:[1,78]},{8:[2,24]},{8:[2,28]},{8:[2,29],22:79,25:$V9,34:$Va,35:$Vb,36:$Vc,37:$Vd,38:$Ve,39:$Vf,40:$Vg,41:$Vh,42:$Vi,43:$Vj,44:$Vk,45:$Vl},{8:[2,31]},{16:80,17:$V7,18:$V8},{24:[1,81]},{24:[1,82]},{23:[1,83]},{24:[1,84]},{33:[1,85]},{8:[2,32]},{21:[1,86]},{21:[1,87]},{24:[1,88]},{21:[1,89]},{8:[2,30]},{8:[2,13]},{8:[2,15]},{21:[1,90]},{8:[2,14]},{8:[2,16]}],
defaultActions: {17:[2,1],27:[2,21],35:[2,20],59:[2,23],61:[2,26],63:[2,25],70:[2,24],71:[2,28],73:[2,31],80:[2,32],85:[2,30],86:[2,13],87:[2,15],89:[2,14],90:[2,16]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    const {declaracion} = require('../Instruction/declaracion');
    const {declaracion1} = require('../Instruction/declaracion1');
    const {declaracion2} = require('../Instruction/declaracion2');
    const {declaracion3} = require('../Instruction/declaracion3');
    const {declaracion4} = require('../Instruction/declaracion4');
    const {etiqueta} = require('../Instruction/etiqueta');
    const {llamada} = require('../Instruction/llamada');
    const {goto} = require('../Instruction/goto');
    const {metodo1} = require('../Instruction/metodo1');
    const {metodo2} = require('../Instruction/metodo2');
    const {imprimir} = require('../Instruction/imprimir');
    const {condicion} = require('../Instruction/condicion');

    var Lista_errores=[];

/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0: this.begin('string'); tmp="";                         
break;
case 1: tmp= tmp+yy_.yytext;   this.begin('string');              
break;
case 2: tmp= tmp+"\n";     this.begin('string');              
break;
case 3: tmp= tmp+"\t";     this.begin('string');              
break;
case 4: tmp= tmp+"\r";     this.begin('string');              
break;
case 5: tmp= tmp+"'";      this.begin('string');              
break;
case 6: tmp= tmp+"";       this.begin('string');              
break;
case 7: this.begin('INITIAL'); yy_.yytext= tmp; return 'STRING'   
break;
case 8:// skip whitespace
break;
case 9:// comentario simple línea
break;
case 10:// comentario multiple líneas
break;
case 11:return 'true'
break;
case 12:return 'false'
break;
case 13:return 18
break;
case 14:return 17
break;
case 15:return 33
break;
case 16:return 'STRING_3'
break;
case 17:return 26
break;
case 18:return '**'
break;
case 19:return '++'
break;
case 20:return '--'
break;
case 21:return 39
break;
case 22:return 41
break;
case 23:return 43
break;
case 24:return 42
break;
case 25:return 44
break;
case 26:return 45
break;
case 27:return 34
break;
case 28:return 25
break;
case 29:return 35
break;
case 30:return 36
break;
case 31:return 37
break;
case 32:return 8
break;
case 33:return 10
break;
case 34:return '.'
break;
case 35:return '?'
break;
case 36:return ','
break;
case 37:return 31
break;
case 38:return 32
break;
case 39:return 38
break;
case 40:return 40
break;
case 41:return '!'
break;
case 42:return 30
break;
case 43:return 23 
break;
case 44:return 28
break;
case 45:return 29
break;
case 46:return 27
break;
case 47:return 19
break;
case 48:return 24
break;
case 49:return 21;
break;
case 50:return 20
break;
case 51:return 5
break;
case 52:  Lista_errores.push("<tr><td>lexico</td><td>No se reconoce el caracter: "+yy_.yytext + "</td><td>" + (yy_.yylineno+1) +'</td><td>'+(yy_.yylloc.first_column+1)+'</td></tr>');	
break;
}
},
rules: [/^(?:["])/i,/^(?:[^"\\])/i,/^(?:[\\][n])/i,/^(?:[\\][t])/i,/^(?:[\\][r])/i,/^(?:[\\]["])/i,/^(?:[\\][\\])/i,/^(?:[\"])/i,/^(?:\s+)/i,/^(?:\/\/.*)/i,/^(?:[\/][*][^*]*[*]+([^\/*][^*]*[*]+)*[\/])/i,/^(?:true\b)/i,/^(?:false\b)/i,/^(?:(([0-9]+)\.([0-9]+)))/i,/^(?:([0-9]+))/i,/^(?:([\'][^']*[\']))/i,/^(?:([\`][^`]*[\`]))/i,/^(?:(printf[^;]*;))/i,/^(?:\*\*)/i,/^(?:\+\+)/i,/^(?:--)/i,/^(?:<=)/i,/^(?:>=)/i,/^(?:!=)/i,/^(?:==)/i,/^(?:&&)/i,/^(?:\|\|)/i,/^(?:\+)/i,/^(?:-)/i,/^(?:\*)/i,/^(?:\/)/i,/^(?:%)/i,/^(?:;)/i,/^(?::)/i,/^(?:\.)/i,/^(?:\?)/i,/^(?:,)/i,/^(?:\[)/i,/^(?:\])/i,/^(?:<)/i,/^(?:>)/i,/^(?:!)/i,/^(?:=)/i,/^(?:\))/i,/^(?:\{)/i,/^(?:\})/i,/^(?:void\b)/i,/^(?:if\b)/i,/^(?:goto\b)/i,/^(?:["(int)"]*([a-zA-Z_])[a-zA-Z0-9_ñÑ]*)/i,/^(?:\()/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"string":{"rules":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52],"inclusive":true},"INITIAL":{"rules":[0,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = Optmizar;
exports.Parser = Optmizar.Parser;
exports.parse = function () { return Optmizar.parse.apply(Optmizar, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}